apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-vms-panda.deepblueai.com
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: cz-vms-panda.deepblueai.com
      http:
        paths:
          - path: /api/v2
            backend:
              serviceName: gateway
              servicePort: 8080
    - host: cz-vms-panda.deepblueai.com
      http:
        paths:
          - path: /api
            backend:
              serviceName: gateway
              servicePort: 8080
  tls:
    - hosts:
        - cz-vms-panda.deepblueai.com
      secretName: deepblueai-certs