apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-prometheus.deepblueai.com
  namespace: prometheus-operator
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: cz-prometheus.deepblueai.com
      http:
        paths:
          - path: /api/v2
            backend:
              serviceName: prometheus-operator-prometheus
              servicePort: 9090