apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-weave-scope-app
  namespace: nacos
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
  #   nginx.ingress.kubernetes.io/secure-backends: "true"
  #   nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  #   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
    - host: weave-console.deepblueai.com
      http:
        paths:
          - path: /
            backend:
              serviceName: weave-scope-app
              servicePort: 80
  tls:
    - hosts:
        - weave-console.deepblueai.com
      secretName: deepblueai-certs