apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-pay.deepblueai.com
  namespace: dbpay
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: cz-pay.deepblueai.com
      http:
        paths:
          - path: /api/v2/
            backend:
              serviceName: dbpay-gateway
              servicePort: 8080
    - host: cz-pay.deepblueai.com
      http:
        paths:
          - path: /api/
            backend:
              serviceName: dbpay-gateway
              servicePort: 8080
    - host: cz-pay.deepblueai.com
      http:
        paths:
          - path: /api/account/
            backend:
              serviceName: dbpay-gateway
              servicePort: 8080
    - host: cz-pay.deepblueai.com
      http:
        paths:
          - path: /api/trade/
            backend:
              serviceName: dbpay-gateway
              servicePort: 8080
  tls:
    - hosts:
        - cz-pay.deepblueai.com
      secretName: deepblueai-certs